### ISSUE TITLE
Take into account delegated democracy votes

### ISSUE THREAD

**Issue by kukabi** [helikon-labs/subvt-backend#187]
Delegated democracy votes are currently not being into taken account when creating "voted" notifications and displaying validator votes under referendum details.

Block indexer should take into account the delegated votes.

**Comment by kukabi** [comment]
Related: https://github.com/helikon-labs/subvt-backend/commit/675aa0c4d491b990ae46cae963f2fc208cf81486

**Comment by MathCryptoDoc** [comment]
Thanks for addressing this so quickly! (It was me that posted the request via the bot.)

**Comment by kukabi** [comment]
Thanks for the report @MathCryptoDoc 🙂

**Comment by kukabi** [comment]
Fixed with v0.13.2.
