### ISSUE TITLE
Feature request - add all validators currently nominated / clear out all validators

### ISSUE THREAD

**Issue by laboon** [helikon-labs/subvt-backend#246]
Instead of manually copy/pasting over changes from my Targets page, it would be nice to just have a command like -

`/setCurrentValidators (nominating stash)`

which would clear out all validators, see which validators (nominating stash) is currently nominating, and add only those.

Alternatively, just having a 

`/clearValidators` or `/removeAllValidators`

which removed all validators from the channel, would save quite a bit of time.

**Comment by kukabi** [comment]
Thanks @laboon, I think it's going to be simple to add `/clearValidators` command, so I'm adding it to my list.

I'll also think about the first one, and if it helps you may use the `/summary` command in the mean time to get an overview of your validators, which also shows which of them are currently active.

**Comment by kukabi** [comment]
`/removeall` command implemented & published.

📝  Leaving the `/setCurrentValidators (nominating stash)` command for the upcoming nominator bot.
