### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by lucasvanmol** [helikon-labs/subvt-backend#303]
The following notification message has bad grammar:

> **Node Name**
> ⭕ is not anymore a paravalidator.

It should be "is not a paravalidator anymore" or "is no longer a paravalidator"

**Comment by kukabi** [comment]
@lucasvanmol thanks so much for the feedback:) It should be fixed now along with some other notifications. I'm closing the issue, please feel free to re-open it if the problem persists.
