### ISSUE TITLE
Keep getting "has unclaimed rewards" even if i do not have any

### ISSUE THREAD

**Issue by frmz** [helikon-labs/subvt-backend#411]
I keep getting the unclaimed rewards message for KSM validator:
GefTiMd4roQrRkJzurdLdGsoAUkmMkiGoYd6Cvu5oqCgamX
Bot says i have unclaimed rewards for ERA 4634, but i have nothing to claim on that era.

**Comment by kukabi** [comment]
@frmz Thanks a lot for the report, I'm going to look into it tomorrow.

**Comment by kukabi** [comment]
In the mean time you may turn off the notification through `/settings`. I'll update here when I post the fix.

**Comment by kukabi** [comment]
@frmz This notification rule has been relaxed, closing this issue for now. Please feel free to reopen it if the issue persists.
